kind: Pod
apiVersion: v1
metadata:
  name: pod-volume
spec:
  containers:
    - name: pod-volume-test
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/tmp"
        name: pod-dynamic
  volumes:
    - name: pod-dynamic
      persistentVolumeClaim:
      - metadata:
        name: mongo-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "fast"
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Gi